# Generated by Django 4.1.6 on 2023-03-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_and_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(max_length=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_and_category.category')),
                ('ProductName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_and_category.product')),
            ],
        ),
    ]
